name: Deploy reveal.js slides to GitHub pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |-
          set -e
          mkdir out
          cp -r images out/
          cp index.css include-in-header.html include-before-body.html include-after-body.html out/
      - uses: docker://pandoc/core:3.1.1
        with:
          args: >-
            index.md -t revealjs -s -o out/index.html --slide-level 3
            -V revealjs-url=https://unpkg.com/reveal.js@5.1.0
            --include-in-header=include-in-header.html
            --include-before-body=include-before-body.html
            --include-after-body=include-after-body.html
            --katex
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: out

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
